const myRecipes = [
  {
    id: "my-1",
    title: "티라미수",
    image: "../img/tiramisu.jpg",
    ingredients: ["egg", "sugar", "mascarpone", "cream", "coffee"],
    source: "local",
    link: "./recipe-tiramisu.html",
  },
  {
    id: "my-2",
    title: "마들렌",
    image: "../img/madulen.jpg",
    ingredients: ["egg", "butter", "sugar", "flour"],
    source: "local",
    link: "./madulen.html",
  },
  {
    id: "my-3",
    title: "가나슈 초콜릿",
    image: "../img/chocolate.jpg",
    ingredients: ["butter", "chocolate", "whipped cream"],
    source: "local",
    link: "./chocolate.html",
  },
  {
    id: "my-4",
    title: "초콜릿 머핀",
    image: "../img/chocolatemuffin.jpg",
    ingredients: [
      "egg",
      "sugar",
      "flour",
      "chocolate",
      "whipped cream",
      "cocoa powder",
    ],
    source: "local",
    link: "./madulen.html",
  },
  {
    id: "my-5",
    title: "빼빼로",
    image: "../img/grinishi.jpg",
    ingredients: [
      "yeast",
      "butter",
      "sugar",
      "flour",
      "chocolate",
      "salt",
      "oil",
    ],
    source: "local",
    link: "./pepero.html",
  },
  {
    id: "my-6",
    title: "브쉬드 노엘",
    image: "../img/브쉬드 노엘.jpg",
    ingredients: [
      "egg",
      "butter",
      "sugar",
      "flour",
      "chocolate",
      "whipped cream",
      "cocoa powder",
    ],
    source: "local",
    link: "./recipe-chocolate.html",
  },
  {
    id: "my-7",
    title: "생크림 케이크",
    image: "../img/grapecake.jpg",
    ingredients: ["egg", "butter", "sugar", "flour", "whipped cream", "fruit"],
    source: "local",
    link: "./recipe-normalcake.html",
  },
];
